In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Salary_Dataset_DataScienceLovers.csv")

In [4]:
df2 = df.copy()

In [14]:
new_rating_oder = [col for col in df2.columns if col != "Rating"] + ["Rating"]
df3 = df2[new_rating_oder].sort_values(["Rating"])
df3

,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles,Rating
2823,TellMe,Android Developer Contractor,144000,1,Pune,Contractor,Android,1.0
10186,Doctily Digital Health,Senior Java Developer,1500000,1,Hyderabad,Full Time,Java,1.0
20182,i-soft software solution,Test Engineer,500000,1,Hyderabad,Full Time,Testing,1.0
7998,VRN Systems,IOS Developer,1100000,1,New Delhi,Full Time,IOS,1.0
18596,Rohan Motors (Dehradun),Software Development Engineer (SDE),500000,1,New Delhi,Full Time,SDE,1.0
...,...,...,...,...,...,...,...,...
9433,Provility,Junior Java Developer,300000,1,Chennai,Full Time,Java,5.0
5095,Talent Zone Consultants,Front End Developer,600000,1,Bangalore,Full Time,Frontend,5.0
85,Blooms Mobility Technologies,Android Developer,300000,1,Bangalore,Full Time,Android,5.0
14277,DataWENS Technologies,Senior Software Development Engineer,648000,1,Chennai,Full Time,SDE,5.0
84,Proven Solution,Android Developer,500000,1,Bangalore,Full Time,Android,5.0

In [21]:
df3.groupby("Company Name")["Salary"].mean().sort_values(ascending=False).reset_index()

                      Company Name      Salary
0                Thapar University  90000000.0
1                     Digital Raju   9800000.0
2                  FFF Enterprises   9800000.0
3           Gaana Lyrics Point.com   9700000.0
4             GGH Heavy Industries   9600000.0
...                            ...         ...
11255   Excel Engineering Services     12000.0
11256        Acmatics Technologies     12000.0
11257  Nasya Software Technologies     12000.0
11258                         ....     12000.0
11259          Keeves Technologies      2112.0

[11260 rows x 2 columns]

In [33]:
df4 = df3.groupby("Job Title").agg(
    Max_Salary = ("Salary", "max"),
    jobsatifaction = ("Rating", "min")).reset_index()

In [35]:
df4.to_json("new_salary.json")

In [37]:
df4.to_excel("demo.xlsx")